# Generated by Django 4.0.3 on 2022-04-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70)),
                ('genre', models.CharField(blank=True, max_length=70)),
                ('starring', models.CharField(blank=True, max_length=70)),
            ],
        ),
    ]
